/* eslint-disable */
export default [
  require('../components/Bubble/bubble-1-bottom.svg'),
  require('../components/Bubble/bubble-1-head.svg'),
  require('../components/Bubble/bubble-1-top.svg'),
  require('../components/Buttons/button-1-hover.svg'),
  require('../components/Buttons/button-1.svg'),
  require('../components/Buttons/button-2-hover.svg'),
  require('../components/Buttons/button-2.svg'),
  require('../components/Buttons/button-3-hover.svg'),
  require('../components/Buttons/button-3.svg'),
  require('../components/DragMe/bubble-2.svg'),
  require('../components/Legs/legs.svg'),
  require('../components/Steps/timeline-1.svg'),
  require('../components/Steps/timeline-2.svg'),
  require('../components/Steps/timeline-3.svg'),
  require('../components/Steps/timeline-4.svg'),
  require('../components/Steps/timeline-5.svg'),
  require('../components/Steps/timeline-6.svg'),
  require('../components/TurnMe/bubble-1.svg'),
  require('../components/Underline/underline-square.svg'),
  require('../containers/HomePage/dr.svg'),
  require('../containers/HomePage/relab-logo.svg'),
  require('../containers/QuizPage/confidence.svg'),
  require('../containers/QuizPage/InputModules/Clock/clock-1.svg'),
  require('../containers/QuizPage/InputModules/Clock/clock-2.svg'),
  require('../containers/QuizPage/InputModules/Clock/clock-face.svg'),
  require('../containers/QuizPage/InputModules/Clock/long hand.svg'),
  require('../containers/QuizPage/InputModules/Clock/short hand.svg'),
  require('../containers/QuizPage/love.svg'),
  require('../containers/QuizPage/nervous.svg'),
  require('../containers/QuizPage/title-icon.svg')
];
